version: "3"

services:
  php:
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
      context: .
    depends_on:
      - redis
    volumes:
      - ./:/app

  redis:
    image: redis:alpine

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.listen-address=:9090'
    depends_on:
      - pushgateway
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml/:/etc/prometheus/prometheus.yml

  pushgateway:
    image: prom/pushgateway
    command:
      - '--web.listen-address=:9191'
    ports:
      - 9191:9191

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./docker/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false