version: "3"

services:
  php:
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
      context: .
    depends_on:
      - redis
    volumes:
      - ./:/app

  redis:
    image: redis:alpine

  haproxy:
    image: haproxy:alpine
    ports:
      - 9190:9190
    volumes:
      - ./docker/haproxy:/usr/local/etc/haproxy:ro

  prometheus:
    image: prom/prometheus
    command:
      - '--web.listen-address=:9090'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
    depends_on:
      - pushgateway
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus1.yml/:/etc/prometheus/prometheus.yml

  pushgateway:
    image: prom/pushgateway
    command:
      - '--web.listen-address=:9191'
      - '--push.disable-consistency-check' # todo: remove this after the pushGatewayClient is fixed
      - '--persistence.interval=5m'
    ports:
      - 9191:9191

  prometheus2:
    image: prom/prometheus
    command:
      - '--web.listen-address=:9091'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
    depends_on:
      - pushgateway2
    ports:
      - 9091:9091
    volumes:
      - ./docker/prometheus/prometheus.yml/:/etc/prometheus/prometheus.yml

  pushgateway2:
    image: prom/pushgateway
    command:
      - '--web.listen-address=:9192'
      - '--push.disable-consistency-check'
      - '--persistence.interval=5m'
    ports:
      - 9192:9192

  prometheus3:
    image: prom/prometheus
    command:
      - '--web.listen-address=:9092'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
    depends_on:
      - pushgateway3
    ports:
      - 9092:9092
    volumes:
      - ./docker/prometheus/prometheus.yml/:/etc/prometheus/prometheus.yml

  pushgateway3:
    image: prom/pushgateway
    command:
      - '--web.listen-address=:9193'
      - '--push.disable-consistency-check'
      - '--persistence.interval=5m'
    ports:
      - 9193:9193

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./docker/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false