parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Comsave\MortyCountsBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Exception,Model,Kernel.php}'

  Prometheus\Storage\Redis:
    factory: ['Comsave\MortyCountsBundle\Factory\RedisStorageAdapterFactory', 'build']
    arguments: ['%comsave_morty_counts.pushgateway.redis%']

  Prometheus\CollectorRegistry:
    autowire: false
    arguments: ['@Prometheus\Storage\Redis']

  GuzzleHttp\Client:
    factory: ['Comsave\MortyCountsBundle\Factory\GuzzleHttpClientFactory', 'build']

  JMS\Serializer\Serializer:
    factory: ['Comsave\MortyCountsBundle\Factory\JmsSerializerFactory', 'build']

  Comsave\MortyCountsBundle\Command\PrometheusPushCommand:
    arguments:
      $prometheusJobNames: '%comsave_morty_counts.prometheus.jobs%'

  Comsave\MortyCountsBundle\Services\PushGateway:
    arguments:
      - '%comsave_morty_counts.pushgateway.host%'
      - '%comsave_morty_counts.pushgateway.username%'
      - '%comsave_morty_counts.pushgateway.password%'

  Comsave\MortyCountsBundle\Services\PushGatewayClient:
    arguments:
      $prometheusInstanceName: '%comsave_morty_counts.prometheus.instance%'

  Comsave\MortyCountsBundle\Services\PrometheusClient:
    arguments:
      $prometheusUrl: '%comsave_morty_counts.prometheus.host%'
      $username: '%comsave_morty_counts.prometheus.username%'
      $password: '%comsave_morty_counts.prometheus.password%'
