parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Comsave\:
    resource: '../src/*'
    exclude: '../src/**/{Enum,Kernel.php}'

  Prometheus\Storage\Redis:
    factory: ['Comsave\MortyCountsBundle\RedisStorageAdapterFactory', 'build']
    arguments: ['%comsave_morty_counts.pushgateway.redis%']

  Prometheus\CollectorRegistry:
    arguments: [Prometheus\Storage\Redis]

  GuzzleHttp\Client:
    factory: ['@Comsave\MortyCountsBundle\GuzzleHttpClientFactory', 'build']

  JMS\Serializer\Serializer:
    factory: ['@Comsave\MortyCountsBundle\JmsSerializerFactory', 'build']

  Comsave\MortyCountsBundle\Command\PrometheusPushCommand:
    autowire: true
    autoconfigure: true
    arguments:
      $prometheusJobNames: '%comsave_morty_counts.prometheus.jobs%'

  Comsave\MortyCountsBundle\Services\PushGateway:
    factory: ['Comsave\MortyCountsBundle\PushGatewayFactory', 'build']
    arguments:
      - '%comsave_morty_counts.pushgateway.host%'
      - '%comsave_morty_counts.pushgateway.username%'
      - '%comsave_morty_counts.pushgateway.password%'

  Comsave\MortyCountsBundle\Services\PushGatewayClient:
    public: true
    autowire: true
    arguments:
      $prometheusInstanceName: '%comsave_morty_counts.prometheus.instance%'

  Comsave\MortyCountsBundle\Services\PrometheusClient:
    public: true
    autowire: true
    arguments:
      $prometheusUrl: '%comsave_morty_counts.prometheus.host%'
      $username: '%comsave_morty_counts.prometheus.username%'
      $password: '%comsave_morty_counts.prometheus.password%'
