parameters:
  morty_counts_pushgateway_url: ''

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Comsave\:
    resource: '../src/*'
    exclude: '../src/**/{Enum,Kernel.php}'

  Prometheus\PushGateway:
    factory: ['Comsave\MortyCountsBundle\PushGatewayFactory', 'build']
    arguments: ['%morty_counts_pushgateway_url%']