parameters:
  morty_counts_prometheus_url: 'prometheus:9090'
  morty_counts_pushgateway_url: 'pushgateway:9191'
  morty_counts_prometheus_instance: 'my_custom_push_service_host_or_other_group_name'
  morty_counts_prometheus_jobs:
    - 'push_job'
  morty_counts_redis_host: 'redis'
  morty_counts_redis_port: 6379

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Comsave\:
    resource: '../src/*'
    exclude: '../src/**/{Enum,Kernel.php}'

  Prometheus\Storage\Redis:
    factory: ['Comsave\MortyCountsBundle\RedisStorageAdapterFactory', 'build']
    arguments:
      $redisHost: '%morty_counts_redis_host%']
      $redisPort: '%morty_counts_redis_port%']

  Prometheus\CollectorRegistry:
    arguments:
      $adapter: Prometheus\Storage\Redis

  GuzzleHttp\Client:
    factory: ['@Comsave\MortyCountsBundle\GuzzleHttpClientFactory', 'build']

  JMS\Serializer\Serializer:
    factory: ['@Comsave\MortyCountsBundle\JmsSerializerFactory', 'build']

  Comsave\MortyCountsBundle\Command\PrometheusPushCommand:
    autowire: true
    autoconfigure: true
    arguments:
      $prometheusJobNames: '%morty_counts_prometheus_jobs%'

  Comsave\MortyCountsBundle\Services\PushGateway:
    factory: ['Comsave\MortyCountsBundle\PushGatewayFactory', 'build']
    arguments:
      $pushGatewayUrl: '%morty_counts_pushgateway_url%']

  Comsave\MortyCountsBundle\Services\PushGatewayClient:
    autowire: true
    arguments:
      $prometheusInstanceName: '%morty_counts_prometheus_instance%'

  Comsave\MortyCountsBundle\Services\PrometheusClient:
    autowire: true
    arguments:
      $prometheusUrl: '%morty_counts_prometheus_url%'
