parameters:
  morty_cuonts_prometheus_url: ''
  morty_counts_pushgateway_url: ''
  morty_counts_redis_host: ''
  morty_counts_redis_port: ''

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Comsave\:
    resource: '../src/*'
    exclude: '../src/**/{Enum,Kernel.php}'

  Prometheus\PushGateway:
    factory: ['Comsave\MortyCountsBundle\PushGatewayFactory', 'build']
    arguments:
      $pushGatewayUrl: '%morty_counts_pushgateway_url%']

  Prometheus\Storage\Redis:
    factory: ['Comsave\MortyCountsBundle\RedisStorageAdapterFactory', 'build']
    arguments:
      $redisHost: '%morty_counts_redis_host%']
      $redisPort: '%morty_counts_redis_port%']

  Prometheus\CollectorRegistry:
    arguments:
      $adapter: Prometheus\Storage\Redis

  GuzzleHttp\Client:
    factory: ['@Comsave\MortyCountsBundle\GuzzleHttpClientFactory', 'build']

  Comsave\MortyCountsBundle\Services\PrometheusClient:
    autowire: true
    arguments:
      $prometheusUrl: '%morty_cuonts_prometheus_url%'